config/routes.rb
Rails.application.routes.draw do
  root 'formats#index'
  resources :formats, only: [:index, :new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_one :user

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/formats_controller.rb
class FormatsController < ApplicationController
  def index
    @formats = Company.includes(:user).all
  end

  def new
    @format = CompanyUser.new
  end

  def create
    @format = CompanyUser.new(format_params)
    if @format.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def format_params
    params.require(:company_user).permit(company_attributes: %i[name address], user_attributes: %i[user_name email password password_confirmation])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formats_helper.rb
module FormatsHelper
end

app/views/formats/index.html.erb
<div class="wrapper">
  <div class="btn">
    <%= link_to '登録する', new_format_path %>
  </div>
  <div class="formats">
    <% @formats.each do |format| %>
      <div class="format">
        <div class="format-name">企業情報：<%= format.name %>/<%= format.address %></div>
        <div class="format-name">ユーザー情報：<%= format.user.user_name%>/<%= format.user.email%></div>
      </div>
    <% end %>
  </div>
</div>

app/views/formats/new.html.erb
<%= form_with(model: @format, url: formats_path, local: false) do |f| %>
  <h1>企業情報</h1>
  <%= f.fields_for :company do |form| %>
  <%= render 'shared/error_message', object: f.object.company %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address %>
  </div>
  <% end %>
  <h1>ユーザー情報</h1>
  <%= f.fields_for :user do |form| %>
  <%= render 'shared/error_message', object: f.object.user %>
    <div class="field">
      <%= form.label :user_name %>
      <%= form.text_field :user_name %>
    </div>
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
    <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
    <div class="field">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit "登録する" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Form</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li> <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>